server:
  servlet:
    context-path: /api
  port: 1212

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aerotek?stringtype=unspecified
    username: postgres
    password: root
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  flyway:
    baseline-on-migrate: true

jwt:
  header: Authorization
  secret: swecor
  expiration: 31536000

upload:
  path: C:/opt/aerotek/content-storage
  path-pdf: C:/opt/aerotek/content-storage/pdf
  owner: SYSTEM

ziehl-abegg:
  username: ZAFS36823
  password: kqv2e2


